### ISSUE TITLE
Reviewer Management: There is no remove reviewer button for an assigned reviewer

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/platform-ui#1031]
There is no remove reviewer button for an assigned reviewer

We can implement this to remove the reviewer via the resources API, similar to the user management functionality.  

<img width="1403" alt="Image" src="https://github.com/user-attachments/assets/af34512e-9000-4de1-87b1-5fb19045d1fa" />

**Comment by phead198708** [comment]
hey, @jmgasper  i can't find related service to deassign the reviewer. Could you pls check ?

**Comment by phead198708** [comment]
we dont' know the role id in review application page, so we can't delete the resource directly (role id is required). 

How about redirect to user management page ? then user can remove reviewer there.

**Comment by jmgasper** [comment]
Yes, that would be fine.

**Comment by phead198708** [comment]
fixed on feat/system-admin branch

![Image](https://github.com/user-attachments/assets/e9e7a1c8-c218-47d2-8a25-ba6ac6716d6e)

**Comment by jmgasper** [comment]
It is still not directing to the correct manage user tab.

Steps to reproduce:

-     Click the Review Management.
-     Click a challenge (goes to challenge details page) and note down the challenge Id. Ex: For DS sc, challenge id: 01671c1c-08d5-42f7-b600-3b254edb8ff4
-     Then click the “Manage Reviewers” button of that particular challenge.
-     Click “Remove reviewer” button for the approved reviewer.
-     Observe the redirection to the Challenge Management → Manage User’s page.

### Expected result:

The redirection on clicking the “Remove reviewer” button should be to the correct challenge’s manage user’s page. Ex: [ https://system-admin.topcoder-dev.com/challenge-management/01671c1c-08d5-42f7-b600-3b254edb8ff4/manage-user ](https://system-admin.topcoder-dev.com/challenge-management/01671c1c-08d5-42f7-b600-3b254edb8ff4/manage-user)

### Actual result:

The redirection on clicking the “Remove reviewer” button is by default going to  https://system-admin.topcoder-dev.com/challenge-management/c713e250-ecb4-4192-8717-d607ddda8db4/manage-user

**Comment by jmgasper** [comment]
From QA:

 Now, even after removing the reviewer from the challenge, the reviewer is still displayed in the Review management page with “Remove Reviewer” button.

Reviewer “Mariokranities” is removed from the challenge but it is still there in the review management page of that particular challenge.

![Image](https://github.com/user-attachments/assets/0d1c2301-a6f7-4080-ab0d-c0a7cc7672fe)

Reviewer “Mariokranities” is not present in the Manage user’s page

![Image](https://github.com/user-attachments/assets/ad983cbc-97cc-46e9-910b-15a0f4a48247)

https://github.com/user-attachments/assets/5850cb39-6dd4-424c-8732-dc3df5861826

### Expected result: 

The reviewer removed from the challenge should not be displayed in the review management page of the challenge.

**Comment by phead198708** [comment]
hmm, actually, the review management page shows the applications of the reviewer. 

Or we can move the remove reviewer button to the top of the table ? if user want to remove the approved application, then we can add a button called 'remove application' at the end of the row.

**Comment by jmgasper** [comment]
Let me think on this - I don't want it to be more confusing.

**Comment by jmgasper** [comment]
@phead198708 - For now, let's just add a "User Management" button at the top of the page that takes the user to the correct resources page for that particular challenge.

We'll remove the `Remove Reviewer` button functionality

**Comment by phead198708** [comment]
resolved in this [PR](https://github.com/topcoder-platform/platform-ui/pull/1093) 

https://github.com/user-attachments/assets/65ddc635-bf87-41ba-acc4-9e4d167e4af1
