### ISSUE TITLE
Reviewer Management: Matching skills are not populated even if there are verified matching skills for the reviewer

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/platform-ui#1033]
### REF: https://topcoder.atlassian.net/browse/PM-937
Reviewer Management: Matching skills are not populated even if there are verified matching skills for the reviewer.

Let's hide this column for now since we don't have that data.

<img width="1390" alt="Image" src="https://github.com/user-attachments/assets/ed0fd6f9-f1d4-4cb3-bd53-e22c59dec5b1" />

**Comment by phead198708** [comment]
fixed

![Image](https://github.com/user-attachments/assets/4c052e6f-8ea2-41c0-996d-d9b5d3b9a168)

**Comment by jmgasper** [comment]
@phead198708 - I still see this as an issue:

![Image](https://github.com/user-attachments/assets/803cf4ac-6025-45bb-843b-b773cc97e2c3)

https://system-admin.topcoder-dev.com/review-management/30096645/manage-reviewer

**Comment by phead198708** [comment]
fixed in feat/system-admin branch

![Image](https://github.com/user-attachments/assets/ab038225-55d1-4769-b70a-4a7a47130143)
