### ISSUE TITLE
Billing Account >> Client: The last button in the pagination section is making the page scroll down to the bottom of the page

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/platform-ui#1034]
### REF: https://topcoder.atlassian.net/browse/PM-1079

Go to https://system-admin.topcoder-dev.com/billing-account/clients 

Do a generic search

Scroll down to the page number section

Click last button

When you click the Last button, the page is scrolled down to the bottom

Note: This issue exists in the Billing accounts page too

https://github.com/user-attachments/assets/71c94f4b-28b6-4a23-8821-16c6044099b7

**Comment by phead198708** [comment]
fixed

https://github.com/user-attachments/assets/a0834e99-d896-484a-a49f-a0019d061050

**Comment by jmgasper** [comment]
QA says this is still an issue:

https://github.com/user-attachments/assets/99bb8115-e059-4ef6-825e-445639ca5836

**Comment by phead198708** [comment]
yeah, I see the issue still existed on https://system-admin.topcoder-dev.com/billing-account/clients

but on https://platform-mvp.topcoder-dev.com/system-admin/billing-account/clients it works well

https://github.com/user-attachments/assets/755c649a-0ce5-4c15-ae37-24dd01a41234

and it works well on branch feat/system-admin as well.

https://github.com/user-attachments/assets/77a8cf20-8661-4397-af85-f0ac1a7a8224
